// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:932ed793-e8e9-4296-b85b-20eb651127d9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_fPGlzSIqF",
    "aws_user_pools_web_client_id": "55ktq56j9bumujbpvpi7kd8j9m",
    "oauth": {}
};


export default awsmobile;
